{
  "Comment": "A description of my state machine",
  "StartAt": "Get Data From API",
  "States": {
    "Get Data From API": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Output": "{% $states.result.Payload %}",
      "Arguments": {
        "FunctionName": "arn:aws:lambda:eu-west-1:257394462879:function:getDataFromApi:$LATEST",
        "Payload": "{% $states.input %}"
      },
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.ServiceException",
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException",
            "Lambda.TooManyRequestsException"
          ],
          "IntervalSeconds": 1,
          "MaxAttempts": 3,
          "BackoffRate": 2,
          "JitterStrategy": "FULL"
        }
      ],
      "Catch": [
        {
          "ErrorEquals": ["States.ALL"],
          "Next": "Handle Get Data Error"
        }
      ],
      "Next": "S3 Data Upload"
    },
    "Handle Get Data Error": {
      "Type": "Fail",
      "Error": "GetDataFromApiFailed",
      "Cause": "An error occurred while getting data from API."
    },
    "S3 Data Upload": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Output": "{% $states.result.Payload %}",
      "Arguments": {
        "FunctionName": "arn:aws:lambda:eu-west-1:257394462879:function:s3DataUpload:$LATEST",
        "Payload": "{% $states.input %}"
      },
      "Retry": [
        {
          "ErrorEquals": [
            "Lambda.ServiceException",
            "Lambda.AWSLambdaException",
            "Lambda.SdkClientException",
            "Lambda.TooManyRequestsException"
          ],
          "IntervalSeconds": 1,
          "MaxAttempts": 3,
          "BackoffRate": 2,
          "JitterStrategy": "FULL"
        }
      ],
      "Catch": [
        {
          "ErrorEquals": ["States.ALL"],
          "Next": "Handle S3 Upload Error"
        }
      ],
      "End": true
    },
    "Handle S3 Upload Error": {
      "Type": "Fail",
      "Error": "S3DataUploadFailed",
      "Cause": "An error occurred while uploading data to S3."
    }
  },
  "QueryLanguage": "JSONata"
}
